repos:
  # Built-in hooks for general file cleanup
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        description: Remove trailing whitespace
      - id: end-of-file-fixer
        description: Ensure files end with newline
      - id: mixed-line-ending
        description: Normalize line endings
      - id: check-merge-conflict
        description: Check for merge conflict markers
      - id: check-yaml
        description: Validate YAML files
      - id: check-json
        description: Validate JSON files

  # Custom QML linting and formatting hooks
  - repo: local
    hooks:
      - id: qml-format
        name: QML Format
        entry: make format
        language: system
        files: '\.qml$'
        description: Format QML files using qmlformat
        pass_filenames: false

      - id: qml-lint
        name: QML Lint
        entry: make lint
        language: system
        files: '\.qml$'
        description: Lint QML files using qmllint
        pass_filenames: false
